default: &default
  adapter: postgresql
  encoding: unicode
  schema_search_path: public
  su_username: postgres
  su_password: postgres1234
  pool: 5

development:
  <<: *default
  host: localhost
  database: haitang_development
  username: postgres
  password: postgres1234

test:
  <<: *default
  host: localhost
  database: haitang_test
  username: postgres
  password: postgres1234

production:
  <<: *default
  host: 127.0.0.1
  database: haitang
  username: youngi
  password: Qq1234567
